version: "3.3"
services:
  db:
    image: "mysql:8.0"
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_TCP_PORT: $MYSQL_PORT
    command:
      - '--skip-log-bin'
      - '--innodb_flush_log_at_trx_commit=2'
      - '--innodb_flush_log_at_timeout=10'
      - '--mysqlx-port=$MYSQLX_PORT'
    volumes:
      - mysql-db:/var/lib/mysql
      - $FRS_HOST_WORKDIR/mysql/01_structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - $FRS_HOST_WORKDIR/mysql/02_default_data.sql:/docker-entrypoint-initdb.d/02_default_data.sql
    network_mode: "host"
  triton:
    image: nvcr.io/nvidia/tritonserver:$TRITON_VERSION-py3
    hostname: triton
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - $FRS_HOST_WORKDIR/model_repository:/models
    entrypoint: ["tritonserver", "--model-repository=/models"]
    network_mode: "host"
  frs:
    image: "lanta/frs"
    volumes:
      - $FRS_HOST_WORKDIR:/opt/frs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    depends_on:
      - db
volumes:
  mysql-db:
